### ISSUE TITLE
can't test actionmailer emails

### ISSUE THREAD

**Issue by langalex** [langalex/culerity#1]
since the web server is running in a different process the emails stored in the test environment are not available to the process that runs the tests. create a file based mailer so that we can still test emails. see http://gist.github.com/110860

**Comment by agibralter** [comment]
This is _kind of_ resolved in the latest, release, right?

I have come across a problem though: AM::Base.clear_deliveries does not work from cucumber steps. Since the culerity instance of the application runs separately from the cucumber instance of the application, calling `clear_deliveries` only deletes persistent email cache file; however, since the culerity instance is also storing the emails in memory (`deliveries << mail` http://github.com/langalex/culerity/blob/master/lib/culerity/persistent_delivery.rb#L25 ), there's no way for the cucumber steps to clear emails mid-scenario.

Here's a possible solution that doesn't store the emails in memory: http://gist.github.com/353664

**Comment by langalex** [comment]
the emails are loaded from the file every time `deliveries` is called so i don't think there should be any problem.

**Comment by agibralter** [comment]
There is a problem though: you can't clear the deliveries reliably and it has to do with your use of "<<". `perform_delivery_persistent` is a instance method and it appears that ActionMailer::Base has an _instance_ variable deliveries (not just the singleton method `ActionMailer::Base.deliveries`).

Your version of `perform_delivery_persistent` appends new mail to the end of the instance variable in _memory_, while `ActionMailer::Base.clear_deliveries` only clears the cache _file_. This leads to a situation where it is impossible to actually `clear_deliveries` from cucumber steps: i.e., even though I call `clear_deliveries`, the next time ActionMailler::Base calls `perform_delivery_persistent` it saves the supposedly deleted email messages to disk again since they are also cached in the `deliveries` instance variable.

The cucumber steps are running in a separate thread from the mongrel app server that listens on localhost:xxxx and where the ActionMailler::Base instance with the `deliveries` instance variable lives. My version of the code http://gist.github.com/353664 simply ensures that mail is not stored in an ActionMailler::Base instance variable but always written to and read from the cache file on disk.

**Comment by langalex** [comment]
so then `perform_delivery_persistent` should clear the `deliveries` variable if the file doesn't exist. wouldn't that solve the problem?

**Comment by agibralter** [comment]
I think that would work as well. http://gist.github.com/353664 essentially does that anyway with `deliveries = self.class.deliveries << mail`.

**Comment by tpo** [comment]
As this is a problem, then is there something holding the fix here from being committed to the repo?

**Comment by tpo** [comment]
I've included that fix in my branch https://github.com/tpo/culerity - it works.

**Comment by langalex** [comment]
just merged it
